<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>VentCalc.UI</AssemblyName>
    <RootNamespace>VentCalc.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VentCalc.Core\VentCalc.Core.csproj" />
  </ItemGroup>
</Project>
